[global]
statistics_update_interval = 1

[ptpengine]
interface = en5             ; REQUIRED NIC (or set via CLI -i)
preset = slaveonly          ; or: slave_only = 1 (both are supported)
domain = 0                  ; domain number
delay_mechanism = E2E
ip_mode = hybrid            ; “mixed” in manpage terms
unicast_negotiation = 0     ; enable negotiation for hybrid/unicast
log_delayreq_interval = 0   ; 0 => 1 Delay_Req per second (log2 seconds)

