/**
 * @file   test_leap_builtin.cpp
 * @brief  Verify the built-in leap-seconds table generated by
 *         scripts/tools/gen-leap-header.py from resources/leap-seconds.list.
 *
 * These tests check the generated *data* directly — no ptpd daemon, no
 * network, no threads.  They run on every platform (macOS, iOS simulator)
 * as part of the macos-gtest preset.
 *
 *   ctest -L unit -R leap
 */

#include <gtest/gtest.h>
#include <ctime>
#include <cstdint>

/* Pull in the generated header directly — it lives in src/def/ which is
 * already on the include path via PTPD_TEST_INCLUDES in src-gtests/CMakeLists. */
extern "C" {
#include "def/leap_seconds_builtin.h"
}

/* NTP epoch offset: seconds between 1900-01-01 and 1970-01-01 */
static constexpr uint32_t kNtpToUnix = 2208988800u;

/* -----------------------------------------------------------------------
 * Table structure sanity
 * ----------------------------------------------------------------------- */

TEST(LeapBuiltin, HasEntries) {
    EXPECT_GT(ptpd_leap_table_count, 0)
        << "Leap table must contain at least one entry";
}

TEST(LeapBuiltin, ExpectedEntryCount) {
    /* Leap-seconds.list from IERS as of early 2025 contains 28 entries
     * (the last insertion was 1 Jan 2017).  Accept ≥ 28. */
    EXPECT_GE(ptpd_leap_table_count, 28)
        << "Expected at least 28 leap-second entries";
}

TEST(LeapBuiltin, TableIsSortedAscending) {
    for (int i = 1; i < ptpd_leap_table_count; ++i) {
        EXPECT_GT(ptpd_leap_table[i].ntp_ts, ptpd_leap_table[i - 1].ntp_ts)
            << "Entry " << i << " NTP timestamp must be > entry " << (i - 1);
    }
}

TEST(LeapBuiltin, OffsetsAreMonotonicallyNonDecreasing) {
    /* TAI - UTC only ever increases (leap seconds are never removed in practice).
     * The table should never have a later entry with a smaller offset. */
    for (int i = 1; i < ptpd_leap_table_count; ++i) {
        EXPECT_GE(ptpd_leap_table[i].tai_offset, ptpd_leap_table[i - 1].tai_offset)
            << "Offset at entry " << i << " decreased unexpectedly";
    }
}

/* -----------------------------------------------------------------------
 * Content correctness for the current (as of 2025) table
 * ----------------------------------------------------------------------- */

TEST(LeapBuiltin, LastEntryOffset37) {
    /* As of 1 Jan 2017 (the last real insertion), TAI - UTC = 37. */
    const int last_idx = ptpd_leap_table_count - 1;
    EXPECT_EQ(ptpd_leap_table[last_idx].tai_offset, 37)
        << "Most recent leap-second entry must have TAI-UTC offset of 37";
}

TEST(LeapBuiltin, LastEntryNtpTimestamp) {
    /* 1 Jan 2017 00:00:00 UTC: Unix = 1483228800, NTP = 1483228800 + 2208988800
     *                                                               = 3692217600 */
    const uint32_t kLeap2017Ntp = 3692217600u;
    const int last_idx = ptpd_leap_table_count - 1;
    EXPECT_EQ(ptpd_leap_table[last_idx].ntp_ts, kLeap2017Ntp)
        << "Last entry should correspond to the 2017-01-01 leap second";
}

/* -----------------------------------------------------------------------
 * Expiry
 * ----------------------------------------------------------------------- */

TEST(LeapBuiltin, ExpiryIsInTheFuture) {
    const uint32_t now_ntp =
        static_cast<uint32_t>(static_cast<int64_t>(std::time(nullptr)) + kNtpToUnix);
    EXPECT_GT(ptpd_leap_table_expiry_ntp, now_ntp)
        << "Built-in table has already expired — rebuild with updated "
           "resources/leap-seconds.list";
}

TEST(LeapBuiltin, ExpiryIsReasonablyFar) {
    /* Expiry should be at least 1 year from now (protects against misconfigured
     * resources/leap-seconds.list being resaved with an old expiry). */
    const uint32_t now_ntp =
        static_cast<uint32_t>(static_cast<int64_t>(std::time(nullptr)) + kNtpToUnix);
    const uint32_t one_year_ntp = 365u * 24u * 3600u;
    EXPECT_GT(ptpd_leap_table_expiry_ntp, now_ntp + one_year_ntp)
        << "Expiry is less than one year away — consider updating "
           "resources/leap-seconds.list";
}

/* -----------------------------------------------------------------------
 * Logical correctness: current UTC offset lookup for "now"
 * ----------------------------------------------------------------------- */

TEST(LeapBuiltin, CurrentOffsetIs37) {
    /* Walk the table exactly as parseLeapTable() does and verify that
     * the resolved currentOffset for today (March 2026) is 37. */
    const uint32_t now_ntp =
        static_cast<uint32_t>(static_cast<int64_t>(std::time(nullptr)) + kNtpToUnix);

    int current_offset = 0;
    for (int i = 0; i < ptpd_leap_table_count; ++i) {
        if (now_ntp >= ptpd_leap_table[i].ntp_ts)
            current_offset = ptpd_leap_table[i].tai_offset;
    }

    EXPECT_EQ(current_offset, 37)
        << "TAI-UTC offset resolved from built-in table should be 37 for "
           "dates between 2017-01-01 and the next (not yet announced) leap second";
}
