#!/usr/bin/env python3
"""
gen-leap-header.py  —  generate src/def/leap_seconds_builtin.h from
                        resources/leap-seconds.list

Usage:
    python3 gen-leap-header.py <src-list-file> <output-header>

Called automatically by the 'leap_header' CMake custom target.
The output file is gitignored and regenerated on every build that detects
a change to resources/leap-seconds.list.
"""

import sys
import re
import datetime

if len(sys.argv) != 3:
    print(f"Usage: {sys.argv[0]} <leap-seconds.list> <output.h>", file=sys.stderr)
    sys.exit(1)

src_path = sys.argv[1]
dst_path = sys.argv[2]

# NTP epoch is 1 Jan 1900; Unix epoch is 1 Jan 1970
NTP_TO_UNIX = 2208988800

entries = []       # list of (ntp_ts, tai_offset, comment)
expiry_ntp = 0
last_update_ntp = 0

with open(src_path) as f:
    for line in f:
        # Last-update marker:   #$  <ntp_ts>
        m = re.match(r'^#\$\s+(\d+)', line)
        if m:
            last_update_ntp = int(m.group(1))

        # Expiry marker:   #@  <ntp_ts>
        m = re.match(r'^#@\s+(\d+)', line)
        if m:
            expiry_ntp = int(m.group(1))

        # Data line:   <ntp_ts>   <tai_offset>   # <comment>
        m = re.match(r'^(\d+)\s+(\d+)\s+#\s+(.+)', line)
        if m:
            entries.append((int(m.group(1)), int(m.group(2)), m.group(3).strip()))

if not entries:
    print(f"ERROR: no leap second entries found in {src_path}", file=sys.stderr)
    sys.exit(1)

if expiry_ntp == 0:
    print(f"ERROR: no expiry timestamp (#@) found in {src_path}", file=sys.stderr)
    sys.exit(1)

expiry_unix = expiry_ntp - NTP_TO_UNIX
expiry_str  = datetime.datetime.fromtimestamp(expiry_unix, tz=datetime.timezone.utc).strftime('%-d %B %Y')

if last_update_ntp:
    update_unix = last_update_ntp - NTP_TO_UNIX
    update_str  = datetime.datetime.fromtimestamp(update_unix, tz=datetime.timezone.utc).strftime('%-d %B %Y')
else:
    update_str = "unknown"

with open(dst_path, 'w') as f:
    f.write(
        "/* AUTO-GENERATED by scripts/tools/gen-leap-header.py — do not edit.\n"
        f" * Source : resources/leap-seconds.list  (updated {update_str})\n"
        f" * Expires: {expiry_str}  (NTP timestamp {expiry_ntp})\n"
        " *\n"
        " * To update: replace resources/leap-seconds.list with the latest file\n"
        " * from https://hpiers.obspm.fr/iers/bul/bulc/ntp/leap-seconds.list\n"
        " * then rebuild. */\n"
        "\n"
        "#ifndef LEAP_SECONDS_BUILTIN_H_\n"
        "#define LEAP_SECONDS_BUILTIN_H_\n"
        "\n"
        "#include <stdint.h>\n"
        "\n"
        "/* One entry per leap second event.\n"
        " * ntp_ts     : NTP timestamp (seconds since 1900-01-01) of the event.\n"
        " * tai_offset : TAI - UTC in seconds, valid from ntp_ts onwards. */\n"
        "typedef struct { uint32_t ntp_ts; int tai_offset; } PtpdLeapEntry;\n"
        "\n"
        "static const PtpdLeapEntry ptpd_leap_table[] = {\n"
    )
    for (ts, offset, comment) in entries:
        f.write(f"    {{ {ts}u, {offset:2d} }},  /* {comment} */\n")
    f.write(
        f"}};\n"
        f"static const int      ptpd_leap_table_count      = {len(entries)};\n"
        f"static const uint32_t ptpd_leap_table_expiry_ntp = {expiry_ntp}u;"
        f"  /* {expiry_str} */\n"
        "\n"
        "#endif /* LEAP_SECONDS_BUILTIN_H_ */\n"
    )

print(f"Generated {dst_path}  ({len(entries)} entries, expires {expiry_str})")
